// src/lib/replicate/local-data/cpt-plugin.ts
//
// Generate a self-contained mu-plugin that registers the CPT + taxonomy + meta
// for the WordPress-driven data path. A mu-plugin (not a one-shot wp-cli call)
// because registration must run on EVERY request — the query loops, REST, and
// block bindings all need the type/taxonomy/meta registered at init, not just
// when posts were inserted. show_in_rest is on everywhere so the block editor's
// query loop + bindings can see the data.
import type { DataModel } from './types.js';

/** PHP single-quoted string literal with ' and \ escaped. */
function php(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Map a DataField type to the WP register_post_meta `type`. */
function metaType(t: 'string' | 'integer' | 'number' | 'boolean'): string {
  return t; // WP accepts 'string' | 'integer' | 'number' | 'boolean' verbatim
}

/**
 * Build the mu-plugin PHP source registering the model's CPT, taxonomy, and
 * per-field post meta. Deterministic + idempotent (WP register_* are safe to
 * call every init). The plugin slug/text is derived from the CPT slug.
 */
export function buildCptMuPlugin(model: DataModel): string {
  const { cpt, taxonomy, fields } = model;
  const supports = `array( ${cpt.supports.map((s) => php(s)).join(', ')} )`;

  const metaRegistrations = fields
    .map(
      (f) =>
        `    register_post_meta( ${php(cpt.slug)}, ${php(f.key)}, array(\n` +
        `        'type'         => ${php(metaType(f.type))},\n` +
        `        'single'       => true,\n` +
        `        'show_in_rest' => true,\n` +
        `    ) );`,
    )
    .join('\n');

  return `<?php
/**
 * Plugin Name: DLA Data — ${cpt.plural}
 * Description: Registers the ${cpt.slug} post type, ${taxonomy.slug} taxonomy, and meta for the WordPress-driven data path (generated by liberate-local).
 *
 * GENERATED FILE — do not edit by hand; re-run the conversion to regenerate.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'init', function () {
    register_post_type( ${php(cpt.slug)}, array(
        'labels'       => array(
            'name'          => ${php(cpt.plural)},
            'singular_name' => ${php(cpt.singular)},
        ),
        'public'       => ${cpt.public ? 'true' : 'false'},
        'has_archive'  => ${cpt.public ? 'true' : 'false'},
        'show_in_rest' => true,
        'supports'     => ${supports},
        'menu_icon'    => 'dashicons-archive',
    ) );

    register_taxonomy( ${php(taxonomy.slug)}, ${php(cpt.slug)}, array(
        'labels'            => array(
            'name'          => ${php(taxonomy.label)},
            'singular_name' => ${php(taxonomy.label)},
        ),
        'public'            => true,
        'hierarchical'      => ${taxonomy.hierarchical ? 'true' : 'false'},
        'show_in_rest'      => true,
        'show_admin_column' => true,
    ) );

${metaRegistrations}
} );
`;
}

/** Conventional mu-plugin filename for a model (under wp-content/mu-plugins/). */
export function cptMuPluginFilename(model: DataModel): string {
  return `dla-data-${model.cpt.slug}.php`;
}
